# Generated by Django 6.1 on 2026-09-27 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, help_text='External service provider (e.g. setu)', max_length=64)),
                ('api_name', models.CharField(db_index=True, help_text='Logical API name (e.g. pan_verification)', max_length=128)),
                ('endpoint_url', models.TextField(help_text='Destination URL')),
                ('http_method', models.CharField(max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Sanitized request headers')),
                ('request_payload', models.JSONField(blank=True, help_text='Sanitized request payload', null=True)),
                ('request_timestamp', models.DateTimeField(db_index=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='Sanitized response headers')),
                ('response_payload', models.JSONField(blank=True, help_text='Sanitized response payload', null=True)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('external_reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_api_logs',
                'ordering': ['-request_timestamp'],
                'indexes': [models.Index(fields=['provider', 'api_name'], name='external_ap_provide_594a81_idx'), models.Index(fields=['is_success', 'request_timestamp'], name='external_ap_is_succ_9b4d5d_idx')],
            },
        ),
    ]
