# Generated by Django 6.1 on 2026-09-27 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan_number', models.CharField(help_text='10-character PAN number', max_length=10)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_id', models.CharField(blank=True, default='', help_text='Setu verification ID', max_length=255)),
                ('registered_name', models.CharField(blank=True, default='', help_text='Name returned from PAN registry', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('aadhaar_seeding_status', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pan_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pan_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
