# Generated by Django 6.1 on 2026-08-13 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitclaim',
            name='claimed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benefitclaim',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_claims', to='groups.group'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='groups.group'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='groups.groupmember'),
        ),
        migrations.AlterUniqueTogether(
            name='benefitclaim',
            unique_together={('group', 'benefit')},
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['group', 'action_type'], name='point_trans_group_i_71a6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['idempotency_key'], name='point_trans_idempot_acffb0_idx'),
        ),
    ]
