# Generated by Django 6.1 on 2026-08-14 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_cached_total_points'),
        ('rewards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='benefitclaim',
            unique_together={('group', 'benefit', 'claimed_by')},
        ),
    ]
