# Generated by Django 6.1 on 2026-08-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group'),
        ),
        migrations.AddField(
            model_name='activity',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='groups.groupmember'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['group', '-created_at'], name='activities_group_i_bb28d6_idx'),
        ),
    ]
