# Generated by Django 6.1 on 2026-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cached_total_points',
            field=models.IntegerField(default=0),
        ),
    ]
